name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        target: [ubuntu_minimal, ubuntu_publisher_circuit_status, ubuntu]
    steps:
      - name: Install GIT
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt-get install -y make gcc-multilib g++-multilib linux-modules-extra-$(uname -r)

      - name: Build and run SITL
        run: |
          ./scripts/vcan.sh slcan0
          make ${{ matrix.target }}
