name: check_crlf

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install dos2unix
      - run: scripts/check_crlf.sh
