name: code_style

on: [push]

jobs:
  cpplint:
    if: false  # disable temporarily
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip3 install cpplint
          sudo apt-get install -y cppcheck dos2unix
      - run: make code_style
