name: code_style

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install cpplint
      - name: cpplint cyphal
        run: |
          cpplint application/*.c application/*.h
          cpplint serialization/*.h serialization/*/*/*.h serialization/*/*/*/*.h
